@startuml
'https://plantuml.com/sequence-diagram


userInput->Solution43: Solution takes in user input\nand reads in necessary info
Solution43->CreateFolders: calls these functions\nwith user input
Solution43->createHTMLFile: calls these functions\nwith user input
CreateFolders->folders: creates necessary folders
createHTMLFile->folders: creates html.index
@enduml